services:
  backend:
    build:
      context: ./hpb-blog-backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./hpb-blog-backend:/app

  frontend:
    build:
      context: ./hpb-blog-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./hpb-blog-frontend:/app
      - /app/node_modules