openapi: 3.1.1
info:
  title: HPB-Blog 系統 API
  description: 針對簡單 HPB-Blog 系統的 API 文件，基於 Go 後端與 Nuxt.js 前端開發。
  version: 1.1.0
servers:
  - url: http://localhost:3000/api
    description: 開發環境伺服器

tags:
  - name: 文章
    description: 與部落格文章相關的操作
  - name: 認證
    description: 使用者身份驗證與授權

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          description: 錯誤代碼。
          example: "錯誤代碼"
        message:
          type: string
          description: 錯誤訊息
          example: "錯誤訊息"

    AuthorInfo:
      type: object
      required: [id, username]
      properties:
        id:
          type: integer
          format: int32
          example: 1
        username:
          type: string
          example: "john_doe"

    Article:
      type: object
      required: [id, author, title, slug, content, created_at, updated_at]
      properties:
        id:
          type: integer
          format: int32
          example: 101
        author:
          $ref: '#/components/schemas/AuthorInfo'
        title:
          type: string
          example: "我的第一篇部落格文章"
        slug:
          type: string
          description: SEO 友善 URL
          example: "my-first-blog-post"
        content:
          type: string
          description: 支援 Markdown 格式
          example: "# 歡迎\n\n這是 **Markdown** 內容。"
        published_at:
          oneOf:
            - type: string
              format: date-time
            - type: "null"
          description: 文章發布時間，未發布為 null
          example: "2023-10-27T10:00:00Z"
        created_at:
          type: string
          format: date-time
          example: "2023-10-27T09:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2023-10-27T09:30:00Z"

    NewArticle:
      type: object
      required: [title, content]
      properties:
        title:
          type: string
          example: "一篇全新的文章"
        content:
          type: string
          example: "這是新文章的 *主體*。"
        slug:
          type: string
          description: 必填
          example: "a-brand-new-article"
        published_at:
          oneOf:
            - type: string
              format: date-time
            - type: "null"

    UpdateArticle:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        slug:
          type: string
        published_at:
          oneOf:
            - type: string
              format: date-time
            - type: "null"

    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
          example: "author_user"
        password:
          type: string
          example: "securepassword123"

    LoginResponse:
      type: object
      required: [token, user]
      properties:
        token:
          type: string
          description: JWT access token
        message:
          type: string
          example: "登入成功"

    PaginatedArticles:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Article'
        meta:
          type: object
          properties:
            total:
              type: integer
              example: 120
            page:
              type: integer
              example: 1
            limit:
              type: integer
              example: 10

  responses:
    BadRequest:
      description: 無效的請求
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: 禁止訪問。這可能是因為身份驗證失敗、權限不足或資源不存在。請檢查請求憑證或您的權限。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 未找到
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: 資源衝突
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unprocessable:
      description: 無法處理的實體
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: 內部伺服器錯誤
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /articles:
    get:
      tags: [文章]
      summary: 取得所有已發布文章
      operationId: getAllArticles
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: 分頁文章列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArticles'
        '500':
          description: 內部伺服器錯誤
          $ref: '#/components/responses/InternalError'

    post:
      tags: [文章]
      summary: 創建新文章
      operationId: createArticle
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewArticle'
      responses:
        '201':
          description: 文章創建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/Unprocessable'
        '500':
          $ref: '#/components/responses/InternalError'

  /articles/{slug}:
    get:
      tags: [文章]
      summary: 依據 slug 取得單一文章
      operationId: getArticleBySlug
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 文章資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      tags: [文章]
      summary: 更新現有文章
      operationId: updateArticle
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
      responses:
        '200':
          description: 文章更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/Unprocessable'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      tags: [文章]
      summary: 刪除文章
      operationId: deleteArticle
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 回傳被刪除的文章
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '204':
          description: 刪除成功，無內容
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/login:
    post:
      tags: [認證]
      summary: 使用者登入
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登入成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
  /auth/logout:
    post:
      tags: [認證]
      summary: 使用者登出
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 登出成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "登出成功"
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
